### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/workspace/MoCoDAD/checkpoints/HR-Avenue/train_experiment'

### ISSUE THREAD

**Issue by LBAMAD** [aleflabo/MoCoDAD#1]
Hi,thank you for your open source of your great work!
However,when i Test MoCoDAD by running the code
> python` eval_MoCoDAD.py --config /args.exp_dir/args.dataset_choice/args.dir_name/config.yaml,

I have the following error,

> File "/workspace/MoCoDAD/eval_MoCoDAD.py", line 39, in <module> out = trainer.test(model, dataloaders=loader, ckpt_path=ckpt_path)
> IsADirectoryError: [Errno 21] Is a directory: '/workspace/MoCoDAD/checkpoints/HR-Avenue/train_experiment'.

How can I solve the problem,hope for your answer,thank you!

**Comment by aleflabo** [comment]
Hi,

I appreciate your interest in our research! 

The problem seems to be related to the 'load_ckpt' parameter of the config you are using. In 'load_ckpt', you should add the name of the checkpoint you want to use ('best_weights.ckpt' for example).

I see in the readme it says "load_ckpt: 'path_to_the_saved_ckpt'", maybe this may confuse. I'm updating it now.

Let me know if this solves the problem.

Alessandro

**Comment by LBAMAD** [comment]
Thank,I have solved it!
Thank for your answer!
