### ISSUE TITLE
some questions about the dataset

### ISSUE THREAD

**Issue by 18764008597** [aleflabo/MoCoDAD#10]
I would like to ask some questions about the dataset. In the process of testing, for example, in the dataset of shanghaiHR, there is only a small part of gt data, while there are a lot of data for testing. How do you finally make the test data correspond to gt data？

**Comment by 18764008597** [comment]
For the shanghai data set, for example, in the first file 01-0014 in its test set, does one file represent a person's trajectory or does the first column of the eight files represent a person's trajectory with the same serial number

**Comment by 18764008597** [comment]
My original understanding is that a file is a person's track, because the 6 frames are divided into the first three frames and the last three frames in the training, but in the final calculation of the auc score in the test, the processing method is to calculate the average value of the data of all csv files in a folder with the same label column and add the difference of the maximum and minimum values after the logarithm transformation of the column. Compare it to real npy data. Why?

**Comment by stdrr** [comment]
Hi, thank you for your interest in our work!

> For the shanghai data set, for example, in the first file 01-0014 in its test set, does one file represent a person's trajectory or does the first column of the eight files represent a person's trajectory with the same serial number

As you correctly guessed, each folder within the folder `trajectories` corresponds to a video clip (e.g., `01-0014`), and each `.csv` file inside the video folder corresponds to a person detected in that clip. In the `.csv` file, there is a row for each frame containing 17 pairs of coordinates `(x,y)` of the person's body joints. Note that some coordinates are set to zero in case of missing detections or joints out of the frame. Also, the rows may not encompass the whole clip length because the person may not appear in some frames.


> My original understanding is that a file is a person's track, because the 6 frames are divided into the first three frames and the last three frames in the training, but in the final calculation of the auc score in the test, the processing method is to calculate the average value of the data of all csv files in a folder with the same label column and add the difference of the maximum and minimum values after the logarithm transformation of the column. Compare it to real npy data. Why?

Consider just a frame of a certain clip. At evaluation time, our method outputs (a set of) predictions for each person that appears in that frame; then, among the predicted poses, we select a predicted pose for each person according to a selection strategy (e.g., taking the prediction that is closest to the ground-truth), ending up with a prediction (or an aggregation of predictions), and thus with an anomaly score value, for each person. Finally, we aggregate the anomaly scores of a frame with the aggregation function you reported.
The `.npy` files are boolean vectors of dimension `(n_videoclip_frames,)` telling which frames within a clip are abnormal and which are not. We compare the (frame-level) anomaly scores of a video clip with its ground truth, dynamically setting the threshold to separate normality from abnormality by maximizing the AUC over the entire test set.  

I am available for any other doubt you may have.

Best regards,
Stefano

**Comment by 18764008597** [comment]
I am very surprised that you could answer me. 
Thank you very much. Based on your reply, I have a new understanding: the npy file that represents the ground truth, such as 01_0014.npy, represents the normal/abnormal status of all frames in this video, and there is more than one person in each frame (here, if one person in a frame is an anomaly, then this frame is represented as an anomaly?). Each csv file in the corresponding folder, such as 01-0014, represents the motion trajectory of a person in the picture, and the first column in the file represents the frame in which the person appears.
In the final calculation of the AUC value, the aggregation function is used to obtain the judgment result of this frame, and the AUC value is calculated by comparing with the result in the npy file.
I don't know if I'm getting this right,Looking forward to your reply.

**Comment by stdrr** [comment]
> here, if one person in a frame is an anomaly, then this frame is represented as an anomaly?

Exactly, a frame is anomalous if at least one person within it is anomalous.

> I don't know if I'm getting this right

Your understanding is correct.

**Comment by 18764008597** [comment]
Ok, thank you very much. Your answer is very helpful to me. I wish you a smooth work and happy life.
