### ISSUE TITLE
In testing. ValueError: need at least one array to stack. 

### ISSUE THREAD

**Issue by ww1e** [aleflabo/MoCoDAD#4]
Hi,thank you for your open source of your great work!
When I want to validate on HR-STC and UBnormal datasets, ValueError: need at least one array to stack. It could be an error caused by the dataset. What should I do? thank you!

**Comment by ww1e** [comment]
File "/data/MoCoDAD-main/eval_MoCoDAD.py", line 28, in <module>
    model.test_on_saved_tensors(split_name=args.split)
  File "/data/MoCoDAD-main/models/mocodad.py", line 456, in test_on_saved_tensors
    auc_score = self.post_processing(tensors['prediction'], tensors['gt_data'], tensors['trans'],
  File "/data/MoCoDAD-main/models/mocodad.py", line 410, in post_processing
    clip_score = np.stack(error_per_person, axis=0)
  File "/home/amax/anaconda3/envs/mocodad/lib/python3.11/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by aleflabo** [comment]
Hi!

Did you modify the config file for evaluation following the suggestions [here](https://github.com/aleflabo/MoCoDAD#once-trained-you-can-run-the-evaluation)?

**Comment by ww1e** [comment]
Sure! I followed this document exactly, and it is worth mentioning that using the HR-Avenue dataset can be correctly evaluated.

**Comment by aleflabo** [comment]
Ok. That's strange.

Are you using the pretrained models or did you train it from scratch?

**Comment by ww1e** [comment]
Both were used for the Avenue dataset, and the pretrained models of the remaining datasets could not be tested correctly. That's what puzzles me.

**Comment by 18764008597** [comment]
Have you solved your problem? I have the same problem.

**Comment by stdrr** [comment]
Hi! Thank you for your interest in our work!

The error you're getting is probably due to `figs_ids` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L386) being empty, causing [this for loop](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L386) to be skipped and the list `error_per_person` be empty as well. This can happen when there is a mismatch between the loaded GT masks and the data being evaluated. 

Could you double-check the paths held by `all_gts` and whether `gt` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L375) is properly loaded? Also, I kindly ask you to show the content of `scene_idx, clip_idx` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L374) before the error happens.

Stefano

P.S.
I see that the issue reported [here](https://github.com/aleflabo/MoCoDAD/issues/4#issuecomment-1857668629) originates from `test_on_saved_tensors` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L433). This function should be called only when the same evaluation has been run at least once and the model's output has been properly saved on disk, which is not the case if you're performing a validation epoch after a training epoch. Can you assure that the error doesn't originate from here and that at least `load_tensors` is set to `false` in the config file? [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/config/UBnormal/mocodad_train.yaml#L83C1-L83C13) and [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/config/UBnormal/mocodad_test.yaml#L82)

**Comment by 18764008597** [comment]
> Hi! Thank you for your interest in our work!
> 
> The error you're getting is probably due to `figs_ids` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L386) being empty, causing [this for loop](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L386) to be skipped and the list `error_per_person` be empty as well. This can happen when there is a mismatch between the loaded GT masks and the data being evaluated. 
> 
> Could you double-check the paths held by `all_gts` and whether `gt` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L375) is properly loaded? Also, I kindly ask you to show the content of `scene_idx, clip_idx` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L374) before the error happens.
> 
> Stefano
> 
> P.S.
> I see that the issue reported [here](https://github.com/aleflabo/MoCoDAD/issues/4#issuecomment-1857668629) originates from `test_on_saved_tensors` [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/models/mocodad.py#L433). This function should be called only when the same evaluation has been run at least once and the model's output has been properly saved on disk, which is not the case if you're performing a validation epoch after a training epoch. Can you assure that the error doesn't originate from here and that at least `load_tensors` is set to `false` in the config file? [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/config/UBnormal/mocodad_train.yaml#L83C1-L83C13) and [here](https://github.com/aleflabo/MoCoDAD/blob/4b34c20c66fa33845562737765fe5fdd212173c9/config/UBnormal/mocodad_test.yaml#L82)

Thank you very much for your reply to me. The reason you mentioned may also cause this problem, but the reason leading to this problem is that the use hr in the config file is not changed to true.
Thanks again for your answers！
